<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>

<body class="min-vh-100 d-flex flex-column">
<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/urls">Сайты</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<?php if (!empty($flashMessages['success'])): ?>
    <div class="alert alert-success" role="alert">
        <?= $flashMessages['success'][0]?>
    </div>
<?php endif; ?>

<?php if (!empty($flashMessages['error'])): ?>
    <div class="alert alert-danger" role="alert">
        <?= $flashMessages['error'][0]?>
    </div>
<?php endif; ?>

<?php if (!empty($flashMessages['successVerification'])): ?>
    <div class="alert alert-success" role="alert">
        <?= $flashMessages['successVerification'][0]?>
    </div>
<?php endif; ?>

<?php if (!empty($flashMessages['errorVerification'])): ?>
    <div class="alert alert-danger" role="alert">
        <?= $flashMessages['errorVerification'][0]?>
    </div>
<?php endif; ?>


<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: <?= $urlData['name'] ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                <tr>
                    <td>ID</td>
                    <td><?= $urlData['id'] ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= $urlData['name'] ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= $urlData['created_at'] ?></td>
                </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form class="mt-5 mb-3" method="post" action="/urls/<?= $urlData['id'] ?>/checks">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover" data-test="checks">
            <tbody>
            <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
            </tr>
            <?php foreach ($urlChecks as $check) : ?>
                <tr>
                    <td><?= $check['id'] ?></td>
                    <td><?= $check['status_code'] ?></td>
                    <td><?= $check['h1'] ?></td>
                    <td><?= $check['title'] ?></td>
                    <td><?= $check['description'] ?></td>
                    <td><?= $check['created_at'] ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</main>

<footer class="border-top py-3 mt-5 flex-shrink-0">
    <div class="container-lg">
        <div class="text-center">
            <a href="https://github.com/pbrackets" target="_blank">pbrackets</a>
        </div>
    </div>
</footer>
</body>

</html>
